CREATE TABLE `user` (  
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT,  
  `USER_NAME` VARCHAR(50) DEFAULT NULL,  
  `USER_PASSWORD` VARCHAR(50) DEFAULT NULL,  
  PRIMARY KEY (`USER_ID`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8; 

DROP TABLE USER;